
repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    rev: v0.0.282
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --non-interactive --install-types
        language: system
        types: [python]
        pass_filenames: true
